### ISSUE TITLE
Section 18.3.8 Decline Reply message

### ISSUE THREAD

**Issue by twintersunh** [dhcwg/rfc8415bis#2]
OLD:
The client includes a Status Code option (see [Section 21.13](https://datatracker.ietf.org/doc/html/rfc8415# section-21.13))
with the value Success, a Server Identifier option (see [Section 21.3(https://datatracker.ietf.org/doc/html/rfc8415#section-21.3)) with the server's DUID, and a Client Identifier option (see [Section 21.2](https://datatracker.ietf.org/doc/html/rfc8415#section-21.2)) with the client's DUID.
NEW:
The server includes a Status Code option....

**Comment by bevolz** [comment]
Hi … not sure what or why this was generated, but this was fixed in 8415bis already.- Bernie (from iPad)On Mar 9, 2023, at 9:55 AM, Timothy Winters ***@***.***> wrote:﻿
OLD:
The client includes a Status Code option (see [Section 21.13](https://datatracker.ietf.org/doc/html/rfc8415# section-21.13))
with the value Success, a Server Identifier option (see [Section 21.3(https://datatracker.ietf.org/doc/html/rfc8415#section-21.3)) with the server's DUID, and a Client Identifier option (see Section 21.2) with the client's DUID.
NEW:
The server includes a Status Code option....

**Comment by twintersunh** [comment]
Already fixed.
